In [2]:
import numpy as np

In [4]:
vector = np.array([1,2,3,4])
print('vector:{}'.format(vector))
print('shape:{}'.format(vector.shape))
print('Dim:{}'.format(vector.ndim))
print('Data Type:{}'.format(vector.dtype))

vector:[1 2 3 4]
shape:(4,)
Dim:1
Data Type:int32


In [9]:
v = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
v.shape = (2,3,2)
v

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [10]:
v = np.zeros((2,3,2))
v

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
v = np.ones((2,3,2))
v

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Arange

The arange function is similar to range function. The data type, if not specified, in many cases will be np.foat64

In [12]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


zeros, zeros_like

zeros(dim) will return a np.array of dim dimensions initialised with 0. Note that dim should be a tuple.

zeros_like(array) will return a np.array of same dimensions as of array initialised with zeros.

same functionality is with ones , and ones_like except of course the initialization is done with ones.
same functionality with empty, and empty_like which will create numpy arrays but won't initialise it with anything (hence, faster) By default, all the values in the array will have garbage values.

In [3]:
print("Zeros")
a = np.zeros((3, 3))
print("A: {}".format(a))
b = np.zeros_like(a)
print("B: {}".format(b))
print("\nOnes")
a = np.ones((3, 3))
print("A: {}".format(a))
b = np.ones_like(a)
print("B: {}".format(b))
print("\nEmpty")
a = np.empty((3, 3))
print("A: {}".format(a))
b = np.empty_like(a)
print("B: {}".format(b))

Zeros
A: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Astype

In [6]:
a = np.array([1,2,3,4.5,6.7])
print('A:{},dtype:{}'.format(a,a.dtype))
b = a.astype(int)
print('B:{},dtype:{}'.format(b,b.dtype))

A:[1.  2.  3.  4.5 6.7],dtype:float64
B:[1 2 3 4 6],dtype:int32


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[1,2,3]])
c= a+b
print(c)

c = a*b
print(c)

c= a-b
print(c)

[[5 7 9]
 [5 7 9]]
[[ 4 10 18]
 [ 4 10 18]]
[[-3 -3 -3]
 [ 3  3  3]]


In [9]:
a = 3
b = np.array([[4,5,6],[1,2,3]])

c = a+b
print(c)

c= a*b
print(c)

c = a-b
print(c)

[[7 8 9]
 [4 5 6]]
[[12 15 18]
 [ 3  6  9]]
[[-1 -2 -3]
 [ 2  1  0]]


In [10]:
a = np.arange(20)
print(a)
a[10:15] = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9  5  5  5  5  5 15 16 17 18 19]


If you want to avoid above scenario, you can use copy()



In [12]:
a = np.arange(20)
print(a)
b = a[10:15].copy()
b = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(arr2d[:,0]) #all rows, first column
print(arr2d[0,:]) #first row, all columns 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]


Boolean indexing

In [17]:
a = np.array(["Mayur", "is", "an", "awesome", "coder"])
a == 'Mayur'

array([ True, False, False, False, False])

In [18]:
#lists entry where value != 'Mayur'
a[~(a=='Mayur')]

array(['is', 'an', 'awesome', 'coder'], dtype='<U7')

In [19]:
(a =='Mayur') | (a =='coder')

array([ True, False, False, False,  True])

In [20]:
a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print(a)
a[[1,3,2]] #it means 1st row, 3rd row, 2nd row

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


array([[2, 2, 2],
       [4, 4, 4],
       [3, 3, 3]])

Transposing

In [21]:
a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print(a.T)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


Universal Functions


In [22]:
a = 20
b = np.random.rand(2,2)
print(np.exp(a))
print(np.exp(b))

485165195.4097903
[[2.22439436 1.03191577]
 [1.21186321 1.51316712]]


meshgrid

One of the most useful function is meshgrid. It's used to visualize data boundaries of your classifier. What you do is train your classifier, then create a meshgrid of every pixel in the plot, and then classify the pixel. When you give the pixel a specific color according to the labelled class you can clearly visualize the boundaries.

Using meshgrid requires three steps.

1.Create xs (1D array)

2.Create ys (1D array)

3.Create meshgrid (2D array) which corresponds to every pixel in the graph.

In [24]:
xs =np.linspace(1,10,100)
ys = np.linspace(1,10,100)

xx,yy = np.meshgrid(xs,ys)
xx,yy
#plot with xx and yy

(array([[ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ],
        [ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ],
        [ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ],
        ...,
        [ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ],
        [ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ],
        [ 1.        ,  1.09090909,  1.18181818, ...,  9.81818182,
          9.90909091, 10.        ]]),
 array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
          1.        ,  1.        ],
        [ 1.09090909,  1.09090909,  1.09090909, ...,  1.09090909,
          1.09090909,  1.09090909],
        [ 1.18181818,  1.18181818,  1.18181818, ...,  1.18181818,
          1.18181818,  1.18181818],
        ...,
        [ 9.81818182,  9.81818182,  9.81818182, ...,  

where

if you have 3 arrays x, y, and condition then, np.where is replacement for using:

if condition: 

    use x
    
else:

    use y

In [25]:
a = [0, -1, 2, 3, -4, -5]
b = [9, 3, 4, 11, 2, 3]
c = [True, False, True, True, False, True]
np.where(c, a, b)
#if c, then a, else b. The first one is True, so we use 0 from a, the second one is False, we use 3 from b.

array([ 0,  3,  2,  3,  2, -5])

Mean, sum, std

In [27]:
a = np.random.rand(3,3)
print(a)
print(np.mean(a))
print(a.mean())

print(np.std(a))

[[0.94370032 0.89965843 0.0818535 ]
 [0.38881269 0.59646802 0.79554422]
 [0.95908005 0.75774381 0.5563255 ]]
0.6643540595530477
0.6643540595530477
0.27440987684923546
